package micro_lua;

public enum TokenType {
    // Palavras-chave
    AND, BREAK, DO, ELSE, ELSEIF, END, FALSE, FOR, FUNCTION, IF, IN,
    LOCAL, NIL, NOT, OR, REPEAT, RETURN, THEN, TRUE, UNTIL, WHILE,

    // Tokens de um ou dois caracteres
    PLUS, MINUS, STAR, SLASH, PERCENT, CARET,
    EQUAL, EQUAL_EQUAL, TILDE_EQUAL,
    LESS, LESS_EQUAL, GREATER, GREATER_EQUAL,
    DOT, DOT_DOT, COLON, SEMICOLON, COMMA,
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
    LEFT_BRACKET, RIGHT_BRACKET, BANG_EQUAL,

    // Literais
    IDENTIFIER, STRING, NUMBER,

    EOF
}